apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.19.0
imageRepository: registry.aliyuncs.com/google_containers
clusterName: kubernetes
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://10.95.10.61:2379"
      advertise-client-urls: "https://10.95.10.61:2379"
      listen-peer-urls: "https://10.95.10.61:2380"
      initial-advertise-peer-urls: "https://10.95.10.61:2380"
      initial-cluster: "dev01-61-k8s=https://10.95.10.61:2380"
    serverCertSANs:
      - dev01-61-k8s
      - 10.95.10.61
    peerCertSANs:
      - dev01-61-k8s
      - 10.95.10.61
networking:
    podSubnet: 10.244.0.0/16
